export const items = [
  {
    id: 1,
    title: 'Leviathan Wakes',
    author: 'James S.A. Corey',
    description: 'A space opera set in a future where humanity has colonized the Solar System',
    imageUrl: 'https://m.media-amazon.com/images/I/51HgrMkErvL._SY346_.jpg',
    linkUrl: 'https://www.amazon.it/Leviathan-Wakes-James-S-Corey/dp/0316129089',
    price: 10.99,
    rating: 4.5,
    releaseDate: '2011',
    publisher: 'Orbit Books'
  },
  {
    id: 2,
    title: 'The Name of the Wind',
    author: 'Patrick Rothfuss',
    description: 'The story of Kvothe, an orphaned musician who becomes a legendary wizard',
    imageUrl: 'https://www.amazon.it/Name-Wind-Kingkiller-Chronicle-Day/dp/0756404746/ref=sr_1_1?__mk_it_IT=%C3%85M%C3%85%C5%BD%C3%95%C3%91&crid=21BNPM1QF8V11&keywords=The+Name+of+the+Wind&qid=1677191000&s=books&sprefix=the+name+of+the+wind%2Cstripbooks%2C92&sr=1-1',
    linkUrl: '',
    price: 12.99,
    rating: 4.7,
    releaseDate: '2007',
    publisher: 'DAW Books'
  },
  {
    id: 3,
    title: 'The Three-Body Problem',
    author: 'Liu Cixin',
    description: 'A science fiction novel about the discovery of an alien civilization',
    imageUrl: 'https://m.media-amazon.com/images/I/41UVrBw8xnL._SY264_BO1,204,203,200_QL40_ML2_.jpg',
    linkUrl: '',
    price: 8.99,
    rating: 4.2,
    releaseDate: '2008',
    publisher: 'Tor Books'
  },
  {
    id: 4,
    title: 'The Fifth Season',
    author: 'N.K. Jemisin',
    description: 'A fantasy novel set in a world wracked by periodic apocalyptic events',
    imageUrl: 'https://m.media-amazon.com/images/I/51X8daq87ZS._SY346_.jpg',
    linkUrl: '',
    price: 9.99,
    rating: 4.6,
    releaseDate: '2015',
    publisher: 'Orbit Books'
  },
  {
    id: 5,
    title: 'The Hunger Games',
    author: 'Suzanne Collins',
    description: 'A dystopian novel set in a future North America where teenagers are forced to fight to the death in an annual televised event',
    imageUrl: 'https://m.media-amazon.com/images/I/41PqRm0q3dL._SX325_BO1,204,203,200_.jpg',
    linkUrl: '',
    price: 7.99,
    rating: 4.5,
    releaseDate: '2008',
    publisher: 'Scholastic Press'
  },
  {
    id: 6,
    title: 'The Lord of the Rings',
    author: 'J.R.R. Tolkien',
    description: 'A classic fantasy epic about a hobbit named Frodo who must destroy a powerful ring before it falls into the hands of an evil lord',
    imageUrl: 'https://m.media-amazon.com/images/I/51kfFS5-fnL._SY264_BO1,204,203,200_QL40_ML2_.jpg',
    linkUrl: '',
    price: 14.99,
    rating: 4.8,
    releaseDate: '1954',
    publisher: 'George Allen & Unwin'
  },
  {
    id: 7,
    title: 'The Windup Girl',
    author: 'Paolo Bacigalupi',
    description: 'A biopunk science fiction novel set in a future Thailand ravaged by global warming and energy shortages',
    imageUrl: 'https://m.media-amazon.com/images/I/4198VGlgxiL._SY264_BO1,204,203,200_QL40_ML2_.jpg',
    linkUrl: '',
    price: 11.99,
    rating: 4.3,
    releaseDate: '2009',
    publisher: 'Night Shade Books'
  },
  {
    id: 8,
    title: 'The Eye of the World',
    author: 'Robert Jordan',
    description: 'The first book in the Wheel of Time series, a high fantasy epic following a group of travelers as they seek to defeat an evil force threatening their world',
    imageUrl: 'https://m.media-amazon.com/images/I/51c3pru+RDL._SY344_BO1,204,203,200_.jpg',
    linkUrl: '',
    price: 9.99,
    rating: 4.4,
    releaseDate: '1990',
    publisher: 'Tor Books'
  },
  {
    id: 9,
    title: 'Red Rising',
    author: 'Pierce Brown',
    description: 'A science fiction novel set on Mars, following a young man\'s journey as he rises through the ranks of a brutal caste system to overthrow the ruling class',
    imageUrl: 'https://m.media-amazon.com/images/I/41AEddrGJ2L._SY264_BO1,204,203,200_QL40_ML2_.jpg',
    linkUrl: '',
    price: 10.99,
    rating: 4.5,
    releaseDate: '2014',
    publisher: 'Del Rey Books'
  },
  {
    id: 10,
    title: 'The Martian',
    author: 'Andy Weir',
    description: 'A science fiction novel about an astronaut stranded on Mars who must use his wits and ingenuity to survive and find a way back to Earth',
    imageUrl: 'https://m.media-amazon.com/images/I/51yaIasZrgL._SY264_BO1,204,203,200_QL40_ML2_.jpg',
    linkUrl: '',
    price: 8.99,
    rating: 4.6,
    releaseDate: '2011',
    publisher: 'Broadway Books'
  },
  {
    id: 11,
    title: 'The Lies of Locke Lamora',
    author: 'Scott Lynch',
    description: 'A high fantasy novel about a group of thieves known as the Gentlemen Bastards who get caught up in a dangerous game of politics and revenge',
    imageUrl: 'https://m.media-amazon.com/images/I/51V1nLdVBiS._SY264_BO1,204,203,200_QL40_ML2_.jpg',
    linkUrl: '',
    price: 11.99,
    rating: 4.4,
    releaseDate: '2006',
    publisher: 'Gollancz'
  },
  {
    id: 12,
    title: 'Hyperion',
    author: 'Dan Simmons',
    description: 'A science fiction novel about a group of pilgrims on a journey to the mysterious planet of Hyperion, where they hope to meet the enigmatic being known as the Shrike',
    imageUrl: 'https://m.media-amazon.com/images/I/51ceO9ZvdyL._SY264_BO1,204,203,200_QL40_ML2_.jpg',
    price: 10.99,
    rating: 4.3,
    releaseDate: '1989',
    publisher: 'Doubleday'
  },
  {
    id: 13,
    title: 'The Dark Tower: The Gunslinger',
    author: 'Stephen King',
    description: 'The first book in King\'s Dark Tower series, following gunslinger Roland Deschain as he travels through a strange and dangerous alternate world in search of the titular tower.',
    imageUrl: 'https://m.media-amazon.com/images/I/41RPv697vYL._SY264_BO1,204,203,200_QL40_ML2_.jpg',
    linkUrl: '',
    price: 11.99,
    rating: 4.3,
    releaseDate: '1982',
    publisher: 'Donald M. Grant/Scribner'
  },
  {
    id: 14,
    title: 'Foundation',
    author: 'Isaac Asimov',
    description: 'The first book in Asimov\'s Foundation series, in which mathematician Hari Seldon creates a plan to save humanity from a predicted 30,000-year-long dark age.',
    imageUrl: 'https://m.media-amazon.com/images/I/41sIWKtP-4L._SY346_.jpg',
    linkUrl: '',
    price: 9.99,
    rating: 4.4,
    releaseDate: '1951',
    publisher: 'Gnome Press'
  },
  {
    id: 15,
    title: 'The Stand',
    author: 'Stephen King',
    description: 'A post-apocalyptic novel in which a superflu wipes out most of the world\'s population, leaving a few survivors to band together and rebuild society.',
    imageUrl: 'https://m.media-amazon.com/images/I/41jUu6y0ooL._SY264_BO1,204,203,200_QL40_ML2_.jpg',
    linkUrl: '',
    price: 13.99,
    rating: 4.5,
    releaseDate: '1978',
    publisher: 'Doubleday'
  },
  {
    id: 16,
    title: 'Ender\'s Game',
    author: 'Orson Scott Card',
    description: 'A science fiction novel about child prodigy Ender Wiggin, who is trained by the military to lead a war against an alien race.',
    imageUrl: 'https://m.media-amazon.com/images/I/51YfSAtW63L.jpg',
    linkUrl: '',
    price: 10.99,
    rating: 4.5,
    releaseDate: '1985',
    publisher: 'Tor Books'
  }
];


